[2025-06-21 17:13:02,547] [INFO] uvicorn.error: Started server process [424]
[2025-06-21 17:13:02,557] [INFO] uvicorn.error: Waiting for application startup.
[2025-06-21 17:13:02,591] [INFO] uvicorn.error: Application startup complete.
[2025-06-21 17:13:27,431] [INFO] app.routes.auth: User found: <app.models.user.User object at 0x000002B4B2653CB0>
[2025-06-21 17:13:27,962] [INFO] app.routes.auth: employee found: <app.models.employee.Employee object at 0x000002B4B27601A0>
[2025-06-21 17:15:48,157] [INFO] uvicorn.error: Shutting down
[2025-06-21 17:15:48,273] [INFO] uvicorn.error: Waiting for application shutdown.
[2025-06-21 17:15:48,300] [INFO] uvicorn.error: Application shutdown complete.
[2025-06-21 17:15:48,309] [INFO] uvicorn.error: Finished server process [424]
[2025-06-21 17:16:00,357] [INFO] uvicorn.error: Started server process [16584]
[2025-06-21 17:16:00,395] [INFO] uvicorn.error: Waiting for application startup.
[2025-06-21 17:16:00,438] [INFO] uvicorn.error: Application startup complete.
[2025-06-21 17:16:13,521] [INFO] uvicorn.error: Shutting down
[2025-06-21 17:16:13,646] [INFO] uvicorn.error: Waiting for application shutdown.
[2025-06-21 17:16:13,666] [INFO] uvicorn.error: Application shutdown complete.
[2025-06-21 17:16:13,666] [INFO] uvicorn.error: Finished server process [16584]
[2025-06-21 17:16:30,450] [INFO] uvicorn.error: Started server process [8636]
[2025-06-21 17:16:30,483] [INFO] uvicorn.error: Waiting for application startup.
[2025-06-21 17:16:30,509] [INFO] uvicorn.error: Application startup complete.
[2025-06-21 17:17:27,010] [INFO] uvicorn.error: Shutting down
[2025-06-21 17:17:27,142] [INFO] uvicorn.error: Waiting for application shutdown.
[2025-06-21 17:17:27,157] [INFO] uvicorn.error: Application shutdown complete.
[2025-06-21 17:17:27,157] [INFO] uvicorn.error: Finished server process [8636]
[2025-06-21 17:17:35,034] [INFO] uvicorn.error: Started server process [12768]
[2025-06-21 17:17:35,051] [INFO] uvicorn.error: Waiting for application startup.
[2025-06-21 17:17:35,068] [INFO] uvicorn.error: Application startup complete.
[2025-06-21 17:17:35,265] [ERROR] uvicorn.error: Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
    self.run_forever()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
    self._run_once()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
    handle._run()
    ~~~~~~~~~~~^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\server.py", line 69, in serve
    with self.capture_signals():
         ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\asyncio\queues.py", line 186, in get
    await getter
asyncio.exceptions.CancelledError

[2025-06-21 17:17:53,936] [INFO] uvicorn.error: Started server process [3568]
[2025-06-21 17:17:53,982] [INFO] uvicorn.error: Waiting for application startup.
[2025-06-21 17:17:54,024] [INFO] uvicorn.error: Application startup complete.
[2025-06-21 17:18:43,069] [INFO] uvicorn.error: Shutting down
[2025-06-21 17:18:43,233] [INFO] uvicorn.error: Waiting for application shutdown.
[2025-06-21 17:18:43,256] [INFO] uvicorn.error: Application shutdown complete.
[2025-06-21 17:18:43,282] [INFO] uvicorn.error: Finished server process [3568]
[2025-06-21 17:18:53,966] [INFO] uvicorn.error: Started server process [19952]
[2025-06-21 17:18:53,984] [INFO] uvicorn.error: Waiting for application startup.
[2025-06-21 17:18:54,006] [INFO] uvicorn.error: Application startup complete.
[2025-06-21 17:18:54,092] [INFO] app.routes.employee: Getting all employees...
[2025-06-21 17:18:54,193] [INFO] app.routes.employee: Getting all employees...
[2025-06-21 17:23:43,069] [INFO] app.routes.employee: Getting all employees...
[2025-06-21 17:23:43,114] [INFO] app.routes.employee: Getting all employees...
[2025-06-21 17:24:02,592] [INFO] app.routes.leave: User request: employee_id=2 start_date=datetime.date(2025, 6, 20) end_date=datetime.date(2025, 6, 21) reason='test' type='CL'
